
export const DEPARTMENTS: string[] = [
    // Especialidades Médicas
    "Alergología",
    "Anatomopatología",
    "Anestesiología",
    "Cardiología",
    "Cardiología Pediátrica",
    "Dermatología",
    "Endocrinología",
    "Endocrinología Pediátrica",
    "Gastroenterología",
    "Gastroenterología Pediátrica",
    "Ginecología y Obstetricia",
    "Hematología",
    "Hematología Pediátrica",
    "Infectología",
    "Infectología Pediátrica",
    "Inmunología",
    "Medicina Interna",
    "Nefrología",
    "Nefrología Pediátrica",
    "Neumonología",
    "Neumonología Pediátrica",
    "Neurocirugía",
    "Neurología",
    "Neurología Pediátrica",
    "Oftalmología",
    "Oftalmología Pediátrica",
    "Oncología y Radioterapia",
    "Otorrinolaringología",
    "Pediatría",
    "Psiquiatría",
    "Reumatología",
    "Traumatología",
    "Urología",
    // Especialidades Quirúrgicas
    "Cirugía Bariátrica",
    "Cirugía Cardiovascular",
    "Cirugía de la Mano",
    "Cirugía de Tórax",
    "Cirugía General",
    "Cirugía Oncológica",
    "Cirugía Pediátrica",
    "Cirugía Plástica",
    "Coloproctología",
    // Servicios de Diagnóstico y Apoyo
    "Bioanálisis",
    "Ecografía",
    "Laboratorio",
    "Medicina Nuclear",
    "Radiología",
    "Rayos X",
    "Tomografía",
    "Unidad de Hemodinamia",
    "Unidosis (Farmacia Hospitalaria)",
    // Estructura Directiva y Gerencial
    "Junta Directiva",
    "Dirección Médica",
    "Fundación Policlínico La Viña",
    "Sociedad Médica",
    // Departamentos Administrativos y de Soporte
    "Gerencia General",
    "Recursos Humanos",
    "Administración y Finanzas",
    "Coordinación de Contabilidad",
    "Analista de Impuestos",
    "Analista de Contabilidad",
    "Gerencia de Seguridad Integral",
    "Departamento Legal",
    "Auditoría Interna",
    "Departamento de Compras",
    "Departamento de Mantenimiento",
    "Departamento de Informática",
];
